# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Connect Tailscale
        # You may pin to the exact commit or the version.
        # uses: tailscale/github-action@cc6818dd6930277a6e4b5d249e32ba2f4cf6ea32
        uses: tailscale/github-action@v1
        with:
          # Your Tailscale authentication key, from the admin panel.
          authkey:  ${{ secrets.TAILSCALE_AUTHKEY }}
    
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pip3 install python-dotenv==0.20.0
          echo "http://nuc:1935/,Get iPlayer" > urls.list
          python3 ./checker.py   
